#ifndef CONFIG_H
#define CONFIG_H
/*This file is generated using python script
                     Any data edited would be lost next time the script run*/

//ENTER_INHALE_MODE_START
#define ENTER_INHALE_MODE_STARTDESIRED_OUTPUT 40.0
#define ENTER_INHALE_MODE_STARTMAXMOTORSPEED 1
#define ENTER_INHALE_MODE_START_DURATION_IN_MS 100.0


//ENTER_INHALE_MODE_REPEAT
#define ENTER_INHALE_MODE_REPEATDESIRED_OUTPUT 80.0
#define ENTER_INHALE_MODE_REPEATMAXMOTORSPEED 1
#define ENTER_INHALE_MODE_REPEAT_DURATION_IN_MS 100.0


//ENTER_INHALE_MODE_LEAVE
#define ENTER_INHALE_MODE_LEAVEDESIRED_OUTPUT 90.0
#define ENTER_INHALE_MODE_LEAVEMAXMOTORSPEED 1
#define ENTER_INHALE_MODE_LEAVE_DURATION_IN_MS 50.0


//RUN_INHALE_MODE_START
#define RUN_INHALE_MODE_STARTDESIRED_OUTPUT 100.0
#define RUN_INHALE_MODE_STARTMAXMOTORSPEED 1
#define RUN_INHALE_MODE_START_DURATION_IN_MS 425.0


//RUN_INHALE_MODE_REPEAT
#define RUN_INHALE_MODE_REPEATDESIRED_OUTPUT 100.0
#define RUN_INHALE_MODE_REPEATMAXMOTORSPEED 1
#define RUN_INHALE_MODE_REPEAT_DURATION_IN_MS 1275.0


//RUN_INHALE_MODE_LEAVE
#define RUN_INHALE_MODE_LEAVEDESIRED_OUTPUT 100.0
#define RUN_INHALE_MODE_LEAVEMAXMOTORSPEED 1
#define RUN_INHALE_MODE_LEAVE_DURATION_IN_MS 425.0


//EXIT_INHALE_MODE_START
#define EXIT_INHALE_MODE_STARTDESIRED_OUTPUT 90.0
#define EXIT_INHALE_MODE_STARTMAXMOTORSPEED 1
#define EXIT_INHALE_MODE_START_DURATION_IN_MS 25.0


//EXIT_INHALE_MODE_REPEAT
#define EXIT_INHALE_MODE_REPEATDESIRED_OUTPUT 70.0
#define EXIT_INHALE_MODE_REPEATMAXMOTORSPEED 1
#define EXIT_INHALE_MODE_REPEAT_DURATION_IN_MS 50.0


//EXIT_INHALE_MODE_LEAVE
#define EXIT_INHALE_MODE_LEAVEDESIRED_OUTPUT 50.0
#define EXIT_INHALE_MODE_LEAVEMAXMOTORSPEED 1
#define EXIT_INHALE_MODE_LEAVE_DURATION_IN_MS 25.0


//ENTER_EXHALE_MODE_START
#define ENTER_EXHALE_MODE_STARTDESIRED_OUTPUT 40.0
#define ENTER_EXHALE_MODE_STARTMAXMOTORSPEED 1
#define ENTER_EXHALE_MODE_START_DURATION_IN_MS 100.0


//ENTER_EXHALE_MODE_REPEAT
#define ENTER_EXHALE_MODE_REPEATDESIRED_OUTPUT 30.0
#define ENTER_EXHALE_MODE_REPEATMAXMOTORSPEED 1
#define ENTER_EXHALE_MODE_REPEAT_DURATION_IN_MS 100.0


//ENTER_EXHALE_MODE_LEAVE
#define ENTER_EXHALE_MODE_LEAVEDESIRED_OUTPUT 20.0
#define ENTER_EXHALE_MODE_LEAVEMAXMOTORSPEED 1
#define ENTER_EXHALE_MODE_LEAVE_DURATION_IN_MS 50.0


//RUN_EXHALE_MODE_START
#define RUN_EXHALE_MODE_STARTDESIRED_OUTPUT 20.0
#define RUN_EXHALE_MODE_STARTMAXMOTORSPEED 1
#define RUN_EXHALE_MODE_START_DURATION_IN_MS 425.0


//RUN_EXHALE_MODE_REPEAT
#define RUN_EXHALE_MODE_REPEATDESIRED_OUTPUT 20.0
#define RUN_EXHALE_MODE_REPEATMAXMOTORSPEED 1
#define RUN_EXHALE_MODE_REPEAT_DURATION_IN_MS 1275.0


//RUN_EXHALE_MODE_LEAVE
#define RUN_EXHALE_MODE_LEAVEDESIRED_OUTPUT 20.0
#define RUN_EXHALE_MODE_LEAVEMAXMOTORSPEED 1
#define RUN_EXHALE_MODE_LEAVE_DURATION_IN_MS 425.0


//EXIT_EXHALE_MODE_START
#define EXIT_EXHALE_MODE_STARTDESIRED_OUTPUT 20.0
#define EXIT_EXHALE_MODE_STARTMAXMOTORSPEED 1
#define EXIT_EXHALE_MODE_START_DURATION_IN_MS 25.0


//EXIT_EXHALE_MODE_REPEAT
#define EXIT_EXHALE_MODE_REPEATDESIRED_OUTPUT 20.0
#define EXIT_EXHALE_MODE_REPEATMAXMOTORSPEED 1
#define EXIT_EXHALE_MODE_REPEAT_DURATION_IN_MS 50.0


//EXIT_EXHALE_MODE_LEAVE
#define EXIT_EXHALE_MODE_LEAVEDESIRED_OUTPUT 30.0
#define EXIT_EXHALE_MODE_LEAVEMAXMOTORSPEED 1
#define EXIT_EXHALE_MODE_LEAVE_DURATION_IN_MS 25.0

#endif //CONFIG_H
